HAI
    BTW variable dec
    I HAS A a ITZ 2
    I HAS A b ITZ 1.5
    I HAS A c ITZ "hello"
    I HAS A d ITZ WIN
    I HAS A e ITZ FAIL
    I HAS A f ITZ QUOSHUNT OF DIFF OF 100 AN WIN AN 3
    DIFF OF PRODUKT OF SUM OF 9 AN 9 AN "2" AN WIN
    OBTW
    I HAS A z ITZ BOTH OF WIN AN FAIL
    TLDR

KTHXBYE